# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    PGHOST
#    PGPORT
#    PGUSER
#    PGPASS
#    PGDATABASE

Default: &defaults
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  database: myblog
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: myblog_test
  <<: *defaults

Staging:
  database: myblog_staging
  poolsize: 100
  <<: *defaults

Production:
  database: myblog_production
  poolsize: 100
  <<: *defaults
